language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
before_script:
  - mysql -u root -e "CREATE DATABASE travisPoc DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON travisPoc.* TO 'root'@'localhost' WITH GRANT OPTION;"
  - mysql -u root -e "CREATE TABLE Users(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(100));"
  - mysql -u root -e "INSERT INTO Users(Name) VALUES('Florin');"
  - mysql -u root -e "INSERT INTO Users(Name) VALUES('Calin');"
  - mysql -u root -e "INSERT INTO Users(Name) VALUES('Petrica');"
 
script:
  - xbuild TravisPOC.sln
  - nunit-console ./TravisPOC/bin/Debug/TravisPOC.exe
